#!/bin/sh
printf "Install AI Tools? [y/N]: "
read -r confirm
case "$confirm" in
    [yY]*) ;;
    *) exit 0 ;;
esac

echo "Installing AI Tools..."
command -v claude || curl -fsSL https://claude.ai/install.sh | bash
command -v opencode || curl -fsSL https://opencode.ai/install | bash
command -v cc-switch || curl -fsSL https://github.com/SaladDay/cc-switch-cli/releases/latest/download/install.sh | bash
