#!/bin/sh
git config --global user.email "84175239+jiesou@users.noreply.github.com"
git config --global user.name "jiesou"
git config --global init.defaultBranch main
git config --global core.quotepath false
git config --global core.compression 9
git config --global commit.gpgsign true
git config --global gpg.format ssh
