#!/bin/bash
read -p "Install AI Tools? [Y/n]: " confirm
[[ "$confirm" != [nN]* ]] && exit 0

echo "Installing AI Tools..."
command -v claude || curl -fsSL https://claude.ai/install.sh | bash
command -v opencode || curl -fsSL https://opencode.ai/install | bash
