monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 600
      }
    }
  }
  {
    matches = [
      {
        node.name = "~alsa_input.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 600
      }
    }
  }
]
