model = "gpt-5.4"
model_reasoning_effort = "high"
[projects."/var/home/chen/Documents/dev/Projects/lceda-gnd-return-path-cal"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/lceda-return-path-cal"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/slint-preview"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/ElectricDriveSystem"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/ElectricDriveCVClient"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/PlatformIOProjects/RobotCar-T1-MicroROS"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/PlatformIOProjects/RobotCar-T1-MicroROS-IDF"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/PlatformIOProjects"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/PlatformIOProjects/AlarmESPMatrix32"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/Playground"]
trust_level = "trusted"

[projects."/var/home/chen/Documents/dev/Projects/Playground/fcitx5-vinput"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"
"gpt-5.2-codex" = "gpt-5.4"

[mcp_servers.context7]
type = "http"
url = "https://mcp.context7.com/mcp"

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[tui]
status_line = ["model-with-reasoning", "context-remaining", "current-dir", "five-hour-limit"]
